<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Traits\Uuids;

class Setting extends Model
{
    use Uuids;


    protected $table = "setting";

    protected $fillable = [
        'nama_instansi',
        'email',
        'antrol_secretkey',
        'antrol_userkey',
        'pcare_penanggung_jawab_claim',
        'regency_id',
        'wilayah_surat',
        'unit_stock_pos',
        'tampilkan_kandungan_obat',
        'batas_bawah_stock',
        'ukuran_surat_sakit',
        'pencarian_rm_lama',
        'tampilan_data_pasien',
        'jenis_range_pemeriksaan_laboratorium',
        'jenis_kop_surat',
        'html_kop_surat',
        'ukuran_surat_sehat',
        'tampilkan_anatomi',
        'filter_pasien_by_dokter',
        'filter_obat_tindakan_bpjs',
        'bayar_dulu_baru_ambil_obat',
        'nomor_spk',
        'pengkajian_awal_ralan',
        'pendaftaran_jenis_identitas_default',
        'filter_jadwal_dokter_berdasarkan_hfis',
        'timezone',
        'otomatis_buka_icare',
        'skema_fee_apoteker',
        'kode_ftkp',
        'no_rekamedis_otomatis',
        'wilayah_bpjs',
        'penanggung_jawab_lab',
        'tampilkan_nominal_dashboard',
        'fonte_token',
        'tampilkan_tindakan_perpoli',
        'status_paperless',
        'status_berlangganan',
        'wa_penjual',
        'aktifkan_penjamin_bpjs',
        'kode_fasyankes',
        'status_ranap',
        'nama_penjual',
        'jenis_kwitansi',
        'biaya_langganan',
        'status_aktif',
        'status_hrm',
        'format_rekam_medis',
        'skrining_resiko_jatuh',
        'layout',
        'nomor_telpon',
        'jenis_member',
        'status_aktif_skrining_visual',
        'tanggal_akhir_berlangganan',
        'alamat',
        'village_id',
        'sinkronisasi_unit_stock',
        'ttv_dilakukan_oleh',
        'logo',
        'jenis_instansi',
        'level',
        'alamat_website',
        'nomor_sertifikat_standar',
        'pcare_status',
        'pcare_consid',
        'gemini_key',
        'pakai_gemini',
        'surat_sakit_pakai_diagnosa',
        'pcare_screet_key',
        'pcare_username',
        'pcare_password',
        'terapkan_ilp',
        'status_inform_consent',
        'pcare_user_key',
        'pcare_tgl_mulai',
        'saldo',
        'icare_username',
        'icare_password',
        'antrol_username',
        'antrol_password',
        'jaksehat_kode',
        'jaksehat_faskes_id',
        'satusehat_status',
        'satusehat_organization_id',
        'satusehat_client_key',
        'satusehat_secret_key',
        'satusehat_env',
        'bpjs_token',
        'kode_pos',
        'bpjs_env',
        'tanggal_mulai_langganan',
        'satusehat_access_token',
        'antrian_link_video',
        'bpjs_kantor_cabang',
        'gunakan_display_antrian',
        'farmasi_boleh_ubah_data',
        'kasir_boleh_ubah_data',
        'format_nomor_surat',
        'vclaim_user_key',
        'vclaim_screet_key',
        'layanan_bpjs_aktif',
        'vclaim_base_url',
        'vclaim_service_name',
        'bpjs_kirim_mcu_otomatis',
        'type_format_nomor_surat_sakit',
        'format_nomor_surat_sakit',
        'type_format_nomor_surat_sehat',
        'format_nomor_surat_sehat',
        'type_format_nomor_surat_rujukan',
        'format_nomor_surat_rujukan',
        'type_format_nomor_surat_buta_warna',
        'format_nomor_surat_buta_warna',
        'type_format_nomor_surat_bebas_narkoba',
        'format_nomor_surat_bebas_narkoba',
        'format_nomor_surat_pengantar_kontrol',
        'type_format_nomor_surat_pengantar_kontrol',
        'type_format_nomor_surat_kehamilan',
        'format_nomor_surat_kehamilan',
        'type_format_nomor_surat_berobat',
        'format_nomor_surat_berobat',
        'display_notifikasi_farmasi',
        'type_format_nomor_surat_berbadan_sehat',
        'format_nomor_surat_berbadan_sehat',
        'type_format_nomor_surat_khitan',
        'format_nomor_surat_khitan',
        'jenis_kop_surat_a5',
        'html_kop_surat_a5',
        'pembagian_jasa_medis',
        'kode_purchase_order_otomatis',
        'kwitansi_per_poli',
        'display_notifikasi_dokter',
        'unit_stock_pesanan_pembelian',
        'jenis_label_obat',
        'type_format_nomor_surat_keterangan_kelahiran',
        'format_nomor_surat_keterangan_kelahiran',
        'timer',
        'timer_status',
        'zoho_item_id',
        'zoho_customer_id',
        'wajib_input_tindakan',
        'sipa_obat',
        'sia_obat',
        'nama_perawat_sipa',
        'nama_apoteker_label',
        'nomor_izin_apotek',
        'nomor_sia',
        'type_format_nomor_surat_skp',
        'format_nomor_surat_skp',
        'setting_nama_desa',
        'pakai_gemini',
        'gemini_key',
        'setting_json',
        'terakhir_login',
        'lab_api_key',
        'aktifkan_reminder_reservasi'
    ];

    protected $casts = [
        'setting_json' => 'array',
    ];

    public function wilayahAdministratifIndonesia()
    {
        return $this->belongsTo('App\Models\WilayahAdministratifIndonesia', 'village_id', 'village_id');
    }

    public function penanggungJawabLab()
    {
        return $this->belongsTo('App\User', 'penanggung_jawab_lab', 'id');
    }

    public function poliklinik()
    {
        return $this->hasMany('App\Models\Poliklinik', 'id', 'poliklinik_id');
    }
}
